name: manual workflow
on:
        workflow_dispatch: 
                inputs:
                        environments:
                                description: "Environment to deploy to"
                                required: false
                                default: "dev"
                                type: string
                        version:
                                description: "version to deploy"
                                required: true
                                type: string
jobs:
        manual-run:
                runs-on: ubuntu-latest

                steps:
                        - name: Print inputs
                          run: |
                                  ehco "Environment: ${{ inputs.environments }}"
                                  echo "Version: ${{ inputs.version }}"


